In [2]:
import numpy as np 


def alignStrings(x,y):
    x = " " + x
    y = " " + y
    length1 = len(x)+1
    length2 = len(y)+1
    c_swap = 1
    c_sub = 1
    c_indel = 1

    #preallocate cost matrix
    Cost_arr = [ [1000]*(length1-1) for _ in range(length2-1) ]

    #initialize cost matrix
    Cost_arr[0][0] = 0
    for i in range(length2-1):
        Cost_arr[i][0] = i
    for j in range(length1-1):
        Cost_arr[0][j] = j
	
	#calculates total cost of next character based on cost of previously aligned characters	
    for i in range(1,length2-1):
        for j in range(1,length1-1):
            if((i < length1-1) and (j < length2-1)): #check index sizes
                    
                    if(x[j] == y[i]): #no op case - the letters are the same! - all cases caught
                        #print("hit NO-OP with case:" ,x[i], y[j], "   i, j:" ,i, j)
                        Cost_arr[i][j] = min(Cost_arr[i][j], Cost_arr[i - 1][j - 1] , Cost_arr[i - 1][j] , Cost_arr[i][j  - 1] )
                        
                    if(i >= 1 and j >=1):
                        
                        if((x[j] == y[i-1]) and  (x[j-1] == y[i])):#check if swap is possible, then use it if it is!
                            #print("hit SWAP with case:" ,x[i], y[j], x[i-1], y[j-1])
                            Cost_arr[i][j] = min(Cost_arr[i][j], Cost_arr[i - 2][j - 2] + c_swap , Cost_arr[i - 1][j - 1] + c_sub, Cost_arr[i - 1][j] + c_indel, Cost_arr[i][j  - 1] + c_indel)
                        
                    
                    #catch cases where indel/swap but pass the initial if
                    Cost_arr[i][j] = min(Cost_arr[i][j], Cost_arr[i - 1][j - 1] + c_sub, Cost_arr[i - 1][j] + c_indel, Cost_arr[i][j  - 1] + c_indel)
            
            else: #cases where the strings have different lengths
                Cost_arr[i][j] = min(Cost_arr[i][j], Cost_arr[i - 1][j - 1] + c_sub, Cost_arr[i - 1][j] + c_indel, Cost_arr[i][j  - 1] + c_indel)
                if(x[j] == y[i]): #no-op in case where the string is longer but it contains a common letter!! (this was a bit of a challenge to find...)
                    Cost_arr[i][j] = min(Cost_arr[i][j], Cost_arr[i - 1][j - 1] , Cost_arr[i - 1][j] , Cost_arr[i][j  - 1] )
                    
                
 
    print(np.matrix(Cost_arr))
    return(Cost_arr)

string1 = 'ape'
string2 = 'step'
costArr = alignStrings(string1,string2)
costArr2 = alignStrings("polynomial", "exponential")
    

[[0 1 2 3]
 [1 1 2 3]
 [2 2 2 3]
 [3 3 3 2]
 [4 4 3 3]]
[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 1  1  2  3  4  5  6  7  8  9 10]
 [ 2  2  2  3  4  5  6  7  8  9 10]
 [ 3  2  3  3  4  5  6  7  8  9 10]
 [ 4  3  2  3  4  5  5  6  7  8  9]
 [ 5  4  3  3  4  4  5  6  7  8  9]
 [ 6  5  4  4  4  5  5  6  7  8  9]
 [ 7  6  5  5  5  4  5  6  7  8  9]
 [ 8  7  6  6  6  5  5  6  7  8  9]
 [ 9  8  7  7  7  6  6  6  6  7  8]
 [10  9  8  8  8  7  7  7  7  6  7]
 [11 10  9  8  9  8  8  8  8  7  6]]
